#!/usr/bin/env bash
# This script manages 'manage_my_process'

#!/usr/bin/env bash
# Manages 'manage_my_process'

if [ $# -gt 0 ]
then
	if [ "$1" == "start" ]
	then
		./manage_my_process &
		touch /var/run/my_process.pid

